services:
  - type: web
    name: pos-system-backend
    env: node
    rootDir: backend
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false # Will be set manually in Render dashboard 