services:
  - type: web
    name: pos-system-backend
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5001
      - key: DATABASE_URL
        sync: false # Will be set manually in Render dashboard 